FROM centos7
MAINTAINER Moussa Balla 
LABEL authors="Moussa Balla"
LABEL description="Container performance "


# Setup some systeme required environment variables

ENV TIMEZONE               "America/New_York"
ENV TERM                    xterm-color
ENV LANG                    en_US.UTF-8
ENV LC_ALL                  c


# Install requierements


