
apiVersion: apps/v1
kind: Deployment

metadata:
  name:

spec:
  selector:
    matchLabels:
      app: nginx
  
  replicas: 2 # tells deploy to run 2 pos matching the template
  template:
    metadata:
      labels:
        app: nginx
     
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPorts: 80 
